import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '../materialTw'
import Header from '@/components/header/Header'
import { CartProvider } from "../hooks/useCart"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kamel Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <CartProvider>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </CartProvider>
      </ThemeProvider>
    </html>
  )
}
